import EncryptedCoinFlipJson from "@/lib/generated-abis/EncryptedCoinFlip.json";
import EncryptedVideoPokerJson from "@/lib/generated-abis/EncryptedVideoPoker.json";
import EncryptedCrashJson from "@/lib/generated-abis/EncryptedCrashGame.json";
import EncryptedDiceJson from "@/lib/generated-abis/EncryptedDiceGame.json";
import EncryptedVaultJson from "@/lib/generated-abis/EncryptedCasinoVault.json";
import EncryptedLiquidityPoolJson from "@/lib/generated-abis/EncryptedLiquidityPool.json";
import EncryptedMarketAMMJson from "@/lib/generated-abis/EncryptedMarketAMM.json";
import EncryptedMarketFactoryJson from "@/lib/generated-abis/EncryptedMarketFactory.json";
import EncryptedMarketResolverJson from "@/lib/generated-abis/EncryptedMarketResolver.json";
import EncryptedPredictionMarketJson from "@/lib/generated-abis/EncryptedPredictionMarket.json";

export const ENCRYPTED_COIN_FLIP_ABI = EncryptedCoinFlipJson;
export const ENCRYPTED_VIDEO_POKER_ABI = EncryptedVideoPokerJson;
export const ENCRYPTED_DICE_ABI = EncryptedDiceJson;
export const ENCRYPTED_CRASH_ABI = EncryptedCrashJson;
export const ENCRYPTED_VAULT_ABI = EncryptedVaultJson;
export const ENCRYPTED_LIQUIDITY_POOL_ABI = EncryptedLiquidityPoolJson;
export const ENCRYPTED_MARKET_AMM_ABI = EncryptedMarketAMMJson;
export const ENCRYPTED_MARKET_FACTORY_ABI = EncryptedMarketFactoryJson;
export const ENCRYPTED_PREDICTION_MARKET_ABI = EncryptedPredictionMarketJson;
export const ENCRYPTED_MARKET_RESOLVER_ABI = EncryptedMarketResolverJson;
export const LIQUIDITY_POOL_ABI = EncryptedLiquidityPoolJson;
export const MARKET_AMM_ABI = EncryptedMarketAMMJson;
export const MARKET_FACTORY_ABI = EncryptedMarketFactoryJson;
export const PREDICTION_MARKET_ABI = EncryptedPredictionMarketJson;
export const MARKET_RESOLVER_ABI = EncryptedMarketResolverJson;
